// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WindowRange.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from WindowRange.proto</summary>
public static partial class WindowRangeReflection {

  #region Descriptor
  /// <summary>File descriptor for WindowRange.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static WindowRangeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFXaW5kb3dSYW5nZS5wcm90byJcChBXaW5kb3dSYW5nZVByb3RvEg0KBXN0",
          "YXJ0GAEgASgBEgsKA2VuZBgCIAEoARIKCgJtehgDIAEoARIOCgZjaGFyZ2UY",
          "BCABKAUSEAoIZmVhdHVyZXMYBSABKAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::WindowRangeProto), global::WindowRangeProto.Parser, new[]{ "Start", "End", "Mz", "Charge", "Features" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class WindowRangeProto : pb::IMessage<WindowRangeProto>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WindowRangeProto> _parser = new pb::MessageParser<WindowRangeProto>(() => new WindowRangeProto());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<WindowRangeProto> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WindowRangeReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WindowRangeProto() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WindowRangeProto(WindowRangeProto other) : this() {
    start_ = other.start_;
    end_ = other.end_;
    mz_ = other.mz_;
    charge_ = other.charge_;
    features_ = other.features_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WindowRangeProto Clone() {
    return new WindowRangeProto(this);
  }

  /// <summary>Field number for the "start" field.</summary>
  public const int StartFieldNumber = 1;
  private double start_;
  /// <summary>
  /// 窗口开始位置
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Start {
    get { return start_; }
    set {
      start_ = value;
    }
  }

  /// <summary>Field number for the "end" field.</summary>
  public const int EndFieldNumber = 2;
  private double end_;
  /// <summary>
  /// 窗口结束位置
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double End {
    get { return end_; }
    set {
      end_ = value;
    }
  }

  /// <summary>Field number for the "mz" field.</summary>
  public const int MzFieldNumber = 3;
  private double mz_;
  /// <summary>
  /// 荷质比
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Mz {
    get { return mz_; }
    set {
      mz_ = value;
    }
  }

  /// <summary>Field number for the "charge" field.</summary>
  public const int ChargeFieldNumber = 4;
  private int charge_;
  /// <summary>
  /// 带电量，使用默认值 -1 表示未知
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Charge {
    get { return charge_; }
    set {
      charge_ = value;
    }
  }

  /// <summary>Field number for the "features" field.</summary>
  public const int FeaturesFieldNumber = 5;
  private string features_ = "";
  /// <summary>
  /// 特征信息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Features {
    get { return features_; }
    set {
      features_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as WindowRangeProto);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(WindowRangeProto other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Start, other.Start)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(End, other.End)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Mz, other.Mz)) return false;
    if (Charge != other.Charge) return false;
    if (Features != other.Features) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Start != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Start);
    if (End != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(End);
    if (Mz != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Mz);
    if (Charge != 0) hash ^= Charge.GetHashCode();
    if (Features.Length != 0) hash ^= Features.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Start != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Start);
    }
    if (End != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(End);
    }
    if (Mz != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Mz);
    }
    if (Charge != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Charge);
    }
    if (Features.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Features);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Start != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Start);
    }
    if (End != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(End);
    }
    if (Mz != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Mz);
    }
    if (Charge != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Charge);
    }
    if (Features.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Features);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Start != 0D) {
      size += 1 + 8;
    }
    if (End != 0D) {
      size += 1 + 8;
    }
    if (Mz != 0D) {
      size += 1 + 8;
    }
    if (Charge != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Charge);
    }
    if (Features.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Features);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(WindowRangeProto other) {
    if (other == null) {
      return;
    }
    if (other.Start != 0D) {
      Start = other.Start;
    }
    if (other.End != 0D) {
      End = other.End;
    }
    if (other.Mz != 0D) {
      Mz = other.Mz;
    }
    if (other.Charge != 0) {
      Charge = other.Charge;
    }
    if (other.Features.Length != 0) {
      Features = other.Features;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          Start = input.ReadDouble();
          break;
        }
        case 17: {
          End = input.ReadDouble();
          break;
        }
        case 25: {
          Mz = input.ReadDouble();
          break;
        }
        case 32: {
          Charge = input.ReadInt32();
          break;
        }
        case 42: {
          Features = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          Start = input.ReadDouble();
          break;
        }
        case 17: {
          End = input.ReadDouble();
          break;
        }
        case 25: {
          Mz = input.ReadDouble();
          break;
        }
        case 32: {
          Charge = input.ReadInt32();
          break;
        }
        case 42: {
          Features = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
